services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    # volumes:
    #   - '/host/path/to/env-config.json:/usr/share/nginx/html/env-config.json'
