/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as adminAdminImport } from './routes/(admin)/_admin'
import { Route as adminAdminXpubImport } from './routes/(admin)/_admin.xpub'
import { Route as adminAdminPaymailsImport } from './routes/(admin)/_admin.paymails'
import { Route as adminAdminDestinationsImport } from './routes/(admin)/_admin.destinations'
import { Route as adminAdminContactsImport } from './routes/(admin)/_admin.contacts'
import { Route as adminAdminAccessKeysImport } from './routes/(admin)/_admin.access-keys'

// Create Virtual Routes

const adminImport = createFileRoute('/(admin)')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const adminRoute = adminImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const adminAdminRoute = adminAdminImport.update({
  id: '/_admin',
  getParentRoute: () => adminRoute,
} as any)

const adminAdminXpubRoute = adminAdminXpubImport.update({
  path: '/xpub',
  getParentRoute: () => adminAdminRoute,
} as any)

const adminAdminPaymailsRoute = adminAdminPaymailsImport.update({
  path: '/paymails',
  getParentRoute: () => adminAdminRoute,
} as any)

const adminAdminDestinationsRoute = adminAdminDestinationsImport.update({
  path: '/destinations',
  getParentRoute: () => adminAdminRoute,
} as any)

const adminAdminContactsRoute = adminAdminContactsImport.update({
  path: '/contacts',
  getParentRoute: () => adminAdminRoute,
} as any)

const adminAdminAccessKeysRoute = adminAdminAccessKeysImport.update({
  path: '/access-keys',
  getParentRoute: () => adminAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/(admin)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminImport
      parentRoute: typeof rootRoute
    }
    '/(admin)/_admin': {
      id: '/_admin'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminAdminImport
      parentRoute: typeof adminRoute
    }
    '/(admin)/_admin/access-keys': {
      id: '/_admin/access-keys'
      path: '/access-keys'
      fullPath: '/access-keys'
      preLoaderRoute: typeof adminAdminAccessKeysImport
      parentRoute: typeof adminAdminImport
    }
    '/(admin)/_admin/contacts': {
      id: '/_admin/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof adminAdminContactsImport
      parentRoute: typeof adminAdminImport
    }
    '/(admin)/_admin/destinations': {
      id: '/_admin/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof adminAdminDestinationsImport
      parentRoute: typeof adminAdminImport
    }
    '/(admin)/_admin/paymails': {
      id: '/_admin/paymails'
      path: '/paymails'
      fullPath: '/paymails'
      preLoaderRoute: typeof adminAdminPaymailsImport
      parentRoute: typeof adminAdminImport
    }
    '/(admin)/_admin/xpub': {
      id: '/_admin/xpub'
      path: '/xpub'
      fullPath: '/xpub'
      preLoaderRoute: typeof adminAdminXpubImport
      parentRoute: typeof adminAdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LoginRoute,
  AboutLazyRoute,
  adminRoute: adminRoute.addChildren({
    adminAdminRoute: adminAdminRoute.addChildren({
      adminAdminAccessKeysRoute,
      adminAdminContactsRoute,
      adminAdminDestinationsRoute,
      adminAdminPaymailsRoute,
      adminAdminXpubRoute,
    }),
  }),
})

/* prettier-ignore-end */
