name: On push changes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main
      - master
      - adminV2

env:
  NODE_VERSION_FILE: 'package.json'
  PACKAGE_MANGER: 'yarn'
  PACKAGE_MANGER_LOCK_FILE: 'yarn.lock'

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: ${{ env.PACKAGE_MANGER }}
          cache-dependency-path: ${{ env.PACKAGE_MANGER_LOCK_FILE }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Code style
        run: |
          yarn prettier:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: ${{ env.PACKAGE_MANGER }}
          cache-dependency-path: ${{ env.PACKAGE_MANGER_LOCK_FILE }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Lint
        run: |
          yarn lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: ${{ env.PACKAGE_MANGER }}
          cache-dependency-path: ${{ env.PACKAGE_MANGER_LOCK_FILE }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Unit test
        run: |
          yarn test:unit

  visual-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: ${{ env.PACKAGE_MANGER }}
          cache-dependency-path: ${{ env.PACKAGE_MANGER_LOCK_FILE }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Run Playwright tests
        run: npx playwright test -c playwright.config.ts

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: |
            test-results/
            !**/*.zip
          retention-days: 3

      - name: Publish Test Summary Results
        run: npx github-actions-ctrf playwright-report/test-results.json
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: ${{ env.PACKAGE_MANGER }}
          cache-dependency-path: ${{ env.PACKAGE_MANGER_LOCK_FILE }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Code style
        run: |
          yarn build
