name: Release
run-name: Release version ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: bactions/workflows/.github/workflows/release-js-server.yml@main
    with:
      version: ${{ github.ref_name }}
    secrets:
#      SLACK_WEBHOOK_URL: ${{ secrets.ON_RELEASE_SLACK_WEBHOOK_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
